services:
  fastapi_app:
    build:
      context: .
      dockerfile: fastapi_app/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env


  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
